### ISSUE TITLE
PM5

### ISSUE THREAD

**Issue by dktapps** [poggit/poggit-phpstan#9]
Supporting both PM4 and PM5 would be ideal

**Comment by JaxkDev** [comment]
Only issue right now is getting the correct/wanted PHP binary. (#3)

**Comment by dktapps** [comment]
Since it's built on the back of the PM Docker image, that shouldn't be an issue?

**Comment by JaxkDev** [comment]
Sorry yes, currently it uses the base image but it’s so outdated right now and requires @SOF3 to build, tag and pull any updated images to update both pmmp and php.
Which is obviously highly inconvenient

**Comment by dktapps** [comment]
I also have push access, I've just rolled a new version of the image to support 8.1.

**Comment by JaxkDev** [comment]
PM4 (4.21.1) and PM5 (5.0.0) Supported.
[c162b81](https://github.com/poggit/poggit-phpstan/commit/c162b8182b8ef0de256dde5306ee2b9592176462)
